import type { Locale } from "@/i18n.config";

export function localizedPath(locale: Locale, path: string) {
  const normalizedPath = path.startsWith("/") ? path : `/${path}`;
  return locale === "en" ? normalizedPath : `/${locale}${normalizedPath}`;
}

export const industryCopy = {
  zh: {
    home: {
      eyebrow: "具身智能产业地图",
      title: "查产品、找企业、提交需求，一站完成具身智能选型",
      description:
        "面向企业决策者、硬件厂商、AI 能力方和投资从业者的结构化信息平台，帮助你更快理解产业链并找到合适合作方。",
      primaryCta: "浏览产品目录",
      secondaryCta: "提交需求",
      searchPlaceholder: "搜索产品、企业或应用场景",
      stats: {
        companies: "收录企业",
        products: "收录产品",
        inquiries: "需求线索",
      },
      entriesTitle: "从一个入口进入行业地图",
      entriesSubtitle: "第一版聚焦产品、企业和需求对接，把最短业务闭环跑通。",
      productEntry: "产品目录",
      productEntryDescription: "按产品类型、应用行业、核心能力筛选机器人和 AI 系统。",
      companyEntry: "企业库",
      companyEntryDescription: "查看硬件厂商、AI 公司、集成商和服务商信息。",
      inquiryEntry: "需求对接",
      inquiryEntryDescription: "提交场景、预算和联系方式，由平台人工协助匹配。",
      newsEntry: "行业资讯",
      newsEntryDescription: "从热点新闻进入相关产品和企业，快速形成选型线索。",
      latestProducts: "最新产品",
      latestCompanies: "最新企业",
      latestNews: "行业资讯",
      sampleNotice: "当前展示示例数据；配置数据库并录入数据后会自动切换为真实内容。",
    },
    products: {
      eyebrow: "产品选型库",
      title: "产品目录",
      description: "按类型、行业、能力和预算检索具身智能产品。",
      search: "搜索产品、厂商或描述",
      keyword: "关键词",
      categoryGroup: "产品类型",
      category: "全部类型",
      industryGroup: "应用行业",
      industry: "全部行业",
      capabilityGroup: "核心能力",
      capability: "全部能力",
      priceRange: "全部预算",
      filter: "筛选",
      filterTitle: "筛选产品",
      clearAll: "清除全部",
      moreFilters: "更多筛选",
      sort: "排序",
      latest: "最新收录",
      popular: "热度优先",
      total: "共 {count} 款产品",
      summaryLabel: "当前匹配产品",
      emptyTitle: "没有找到匹配产品",
      emptyDescription: "换一个关键词或筛选条件再试试。",
      sampleNotice: "预览模式：当前为示例数据。",
    },
    companies: {
      eyebrow: "企业情报库",
      title: "企业库",
      description: "检索具身智能产业链上下游企业，快速建立供应商地图。",
      search: "搜索企业、领域或简介",
      keyword: "关键词",
      typeGroup: "企业类型",
      type: "全部类型",
      location: "国家或城市",
      fundingStageGroup: "融资阶段",
      fundingStage: "全部融资阶段",
      filter: "筛选",
      filterTitle: "筛选企业",
      clearAll: "清除全部",
      moreFilters: "更多筛选",
      total: "共 {count} 家企业",
      summaryLabel: "当前匹配企业",
      emptyTitle: "没有找到匹配企业",
      emptyDescription: "换一个关键词或筛选条件再试试。",
      sampleNotice: "预览模式：当前为示例数据。",
    },
    news: {
      eyebrow: "行业资讯",
      title: "具身智能资讯",
      description: "追踪政策、融资、产品发布和应用案例，并关联到可继续了解的产品与企业。",
      search: "搜索标题、来源、标签或正文",
      keyword: "关键词",
      categoryGroup: "资讯分类",
      category: "全部分类",
      filter: "筛选",
      filterTitle: "筛选资讯",
      clearAll: "清除全部",
      moreFilters: "更多筛选",
      sort: "排序",
      latest: "最新发布",
      hot: "热度优先",
      summaryLabel: "当前匹配资讯",
      emptyTitle: "没有找到匹配资讯",
      emptyDescription: "换一个关键词或分类再试试。",
      sampleNotice: "预览模式：当前为示例数据。",
    },
    detail: {
      backProducts: "返回产品目录",
      backCompanies: "返回企业库",
      backNews: "返回资讯列表",
      inquire: "提交需求",
      official: "访问官网",
      source: "资讯来源",
      publishedAt: "发布时间",
      hotScore: "热度",
      company: "所属企业",
      specs: "产品参数",
      scenarios: "应用场景",
      relatedProducts: "相关产品",
      relatedCompanies: "相关企业",
      companyProducts: "旗下产品",
      profile: "企业介绍",
      basicInfo: "基础信息",
      noDescription: "暂无详细介绍。",
      newsBody: "资讯正文",
      newsCtaTitle: "想基于这条资讯继续了解产品或企业？",
      newsCtaDescription: "提交你的场景和预算，平台运营会根据资讯关联的产品、企业和应用方向协助匹配。",
    },
    inquiry: {
      eyebrow: "需求匹配",
      title: "提交需求",
      description: "描述你的业务场景，平台运营会人工协助匹配合适厂商、产品或解决方案。",
      asideTitle: "适合提交的需求",
      asideItems: [
        "需要了解某类机器人或 AI 系统供应商",
        "正在做自动化、巡检、搬运、交互等场景选型",
        "希望平台帮助判断预算、产品路线或合作对象",
      ],
      formEyebrow: "需求对接",
      formTitle: "告诉我们你的场景",
      sourceHintDefault: "填写需求后，平台运营会人工判断并协助匹配合适厂商或产品。",
      sourceHintWithName: "当前咨询对象：{name}",
      sourceBadgeProduct: "来自产品详情",
      sourceBadgeCompany: "来自企业详情",
      sourceBadgeNews: "来自资讯详情",
      sourceBadgeGeneral: "来自通用入口",
      scenarioPrefill: "我想了解 {name}，希望平台协助对接合适方案。",
      labels: {
        name: "姓名",
        companyName: "公司名称",
        email: "邮箱",
        phone: "手机",
        industry: "所属行业",
        budgetRange: "预算范围",
        scenario: "需求场景",
        message: "补充说明",
      },
      placeholders: {
        name: "请输入姓名",
        companyName: "公司或机构名称",
        email: "hello@example.com",
        phone: "方便联系的手机号",
        industry: "请选择行业",
        budgetUnknown: "暂不确定",
        scenario: "例如：工厂夜间巡检、仓库搬运、展厅互动、医疗康复辅助...",
        message: "可以补充时间计划、已有设备、对接系统、地区要求等。",
      },
      successTitle: "提交成功",
      successMessage: "需求已提交，我们会尽快处理。",
      continueLabel: "继续提交",
      submitLabel: "提交需求",
      submittingLabel: "提交中...",
      errorFallback: "提交失败，请稍后重试。",
      networkError: "网络异常，请稍后重试。",
    },
  },
  en: {
    home: {
      eyebrow: "Embodied AI industry map",
      title: "Find products, map vendors, and submit buying needs in one place",
      description:
        "A structured information platform for decision makers, hardware vendors, AI providers, and investors tracking the embodied intelligence ecosystem.",
      primaryCta: "Browse Products",
      secondaryCta: "Submit Inquiry",
      searchPlaceholder: "Search products, companies, or use cases",
      stats: {
        companies: "Companies",
        products: "Products",
        inquiries: "Inquiries",
      },
      entriesTitle: "Start from the shortest industry workflow",
      entriesSubtitle: "The first version focuses on product discovery, company discovery, and lead handoff.",
      productEntry: "Product Directory",
      productEntryDescription: "Filter robots and AI systems by category, industry, and capability.",
      companyEntry: "Company Database",
      companyEntryDescription: "Explore hardware makers, AI companies, integrators, and service providers.",
      inquiryEntry: "Inquiry Matching",
      inquiryEntryDescription: "Submit your use case and budget so the platform team can route it manually.",
      newsEntry: "Industry News",
      newsEntryDescription: "Turn hot news into related products, vendors, and actionable inquiries.",
      latestProducts: "Latest Products",
      latestCompanies: "Latest Companies",
      latestNews: "Industry News",
      sampleNotice: "Showing sample data until a database is configured and real records are added.",
    },
    products: {
      eyebrow: "Product directory",
      title: "Product Directory",
      description: "Search embodied AI products by type, industry, capability, and budget.",
      search: "Search products, vendors, or descriptions",
      keyword: "Keyword",
      categoryGroup: "Product type",
      category: "All categories",
      industryGroup: "Industry",
      industry: "All industries",
      capabilityGroup: "Capability",
      capability: "All capabilities",
      priceRange: "All budgets",
      filter: "Filter",
      filterTitle: "Filter products",
      clearAll: "Clear all",
      moreFilters: "More filters",
      sort: "Sort",
      latest: "Newest",
      popular: "Most popular",
      total: "{count} products",
      summaryLabel: "Matching products",
      emptyTitle: "No products found",
      emptyDescription: "Try a different keyword or filter.",
      sampleNotice: "Preview mode: sample data is being shown.",
    },
    companies: {
      eyebrow: "Company database",
      title: "Company Database",
      description: "Search the embodied AI supply chain and build a vendor map quickly.",
      search: "Search companies, domains, or descriptions",
      keyword: "Keyword",
      typeGroup: "Company type",
      type: "All types",
      location: "Country or city",
      fundingStageGroup: "Funding stage",
      fundingStage: "All funding stages",
      filter: "Filter",
      filterTitle: "Filter companies",
      clearAll: "Clear all",
      moreFilters: "More filters",
      total: "{count} companies",
      summaryLabel: "Matching companies",
      emptyTitle: "No companies found",
      emptyDescription: "Try a different keyword or filter.",
      sampleNotice: "Preview mode: sample data is being shown.",
    },
    news: {
      eyebrow: "Industry news",
      title: "Embodied AI News",
      description: "Track policies, funding, product launches, and application cases with related products and companies attached.",
      search: "Search titles, sources, tags, or article body",
      keyword: "Keyword",
      categoryGroup: "News category",
      category: "All categories",
      filter: "Filter",
      filterTitle: "Filter news",
      clearAll: "Clear all",
      moreFilters: "More filters",
      sort: "Sort",
      latest: "Newest",
      hot: "Most popular",
      summaryLabel: "Matching articles",
      emptyTitle: "No articles found",
      emptyDescription: "Try a different keyword or category.",
      sampleNotice: "Preview mode: sample data is being shown.",
    },
    detail: {
      backProducts: "Back to products",
      backCompanies: "Back to companies",
      backNews: "Back to news",
      inquire: "Submit inquiry",
      official: "Visit website",
      source: "Source",
      publishedAt: "Published",
      hotScore: "Hot score",
      company: "Company",
      specs: "Specifications",
      scenarios: "Use cases",
      relatedProducts: "Related products",
      relatedCompanies: "Related companies",
      companyProducts: "Company products",
      profile: "Company profile",
      basicInfo: "Basic info",
      noDescription: "No detailed description yet.",
      newsBody: "Article",
      newsCtaTitle: "Want to turn this news into a product or vendor shortlist?",
      newsCtaDescription: "Submit your use case and budget. The platform team will route it based on the linked products, companies, and application direction.",
    },
    inquiry: {
      eyebrow: "Inquiry matching",
      title: "Submit Inquiry",
      description: "Describe your use case. The platform team will manually help match vendors, products, or solutions.",
      asideTitle: "Good fit for",
      asideItems: [
        "Finding suppliers for a robot or AI system category",
        "Evaluating automation, inspection, handling, or interaction scenarios",
        "Getting help with budget, product direction, or partner matching",
      ],
      formEyebrow: "Inquiry matching",
      formTitle: "Tell us about your use case",
      sourceHintDefault: "After you submit, the platform team will review it and route suitable vendors or products manually.",
      sourceHintWithName: "Current inquiry target: {name}",
      sourceBadgeProduct: "From product detail",
      sourceBadgeCompany: "From company detail",
      sourceBadgeNews: "From news detail",
      sourceBadgeGeneral: "From general entry",
      scenarioPrefill: "I would like to learn more about {name} and get help matching the right solution.",
      labels: {
        name: "Name",
        companyName: "Company",
        email: "Email",
        phone: "Phone",
        industry: "Industry",
        budgetRange: "Budget range",
        scenario: "Use case",
        message: "Additional notes",
      },
      placeholders: {
        name: "Your name",
        companyName: "Company or organization",
        email: "hello@example.com",
        phone: "Best contact number",
        industry: "Select an industry",
        budgetUnknown: "Not sure yet",
        scenario: "For example: factory inspection, warehouse handling, showroom interaction, rehabilitation assistance...",
        message: "Add timeline, existing equipment, integration needs, region requirements, or anything else.",
      },
      successTitle: "Submitted",
      successMessage: "Your inquiry has been submitted. We will review it soon.",
      continueLabel: "Submit another",
      submitLabel: "Submit inquiry",
      submittingLabel: "Submitting...",
      errorFallback: "Submission failed. Please try again later.",
      networkError: "Network error. Please try again later.",
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;
